[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesting_contract = "5CzpYVBLG6akeQqbcGABdxffnCSmNqYDJc2JL7ZLe5jw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wsl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
