[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesting_contract = "GZ5Q5XdSv4PARXMn5ZGAvF7KjafLStsCGwEAzjowpqsw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
deploy = "anchor build && anchor deploy --provider.wallet ./tests/vanity_accounts/testWroMBjmRex6dkA6UkcLQq8cSMLfSVmgAJFi6zoV.json"
